Dev bboxes
luca-nickel/aircraft-classification pull request #7
Opened 2024-05-10 13:04 UTC by Agueney

fixed version 1 working, added new struc, added custom dataloader for boxes, working version 1.

2024-05-11 20:23 UTC, luca-nickel requested changes
Generell viele Case Style Errors, fehlende Docstrings und komische Variablennamen, die das ganz ziemlich unleserlich machen für Leute, die den Code nicht geschrieben haben. Kann ich leider nicht alleine ändern. Müssen wir mal drüber gucken.

2024-05-11 20:23 UTC, luca-nickel commented on src/preprocessing/config_loader.py
Diese Klasse ist ehrlich gesagt ein bisschen unnötig. Dasselbe kann man in 4 Zeilen machen, siehe [hier](https://stackoverflow.com/questions/1773805/how-can-i-parse-a-yaml-file-in-python)

2024-05-11 20:23 UTC, luca-nickel commented on src/bounding_boxes/model_architecture/CNN_bounding_boxes_architecture.py
Bitte Klassennamen fixen & wieso out_channels in Capslock?

2024-05-11 20:23 UTC, luca-nickel commented on src/bounding_boxes/fgvs_aircraft_custom_dataset.py
Hast du hier einfach den Code vom FGVC Dataset kopiert und überschrieben? Kannst du nicht einfach von der Klasse erben und sie so erweitern, wie du möchtest?

2024-05-11 20:23 UTC, luca-nickel commented on src/bounding_boxes/bounding_box_training_exe.py
Bitte fixen: Klassenname, absoluter Pfad, Methodenname (exe?), Imports (einmal logging.export... und dann src.bounding_boxes..., bitte vereinheitlichen). Variablennamen (kein Capslock, kein camelCase, nur snake_case). Wieso nennst du die Klasse Exe? Exe steht für Executable, also ausführbare Dateien, aber das ist es nicht. "Bounding Box Training" heißt ja, das soll ein Training darstellen. Wieso muss das eine Klasse sein, kannst du das nicht in einer Config alles speichern und von der Trainer Klasse ausführen lassen?

2024-05-11 20:23 UTC, luca-nickel commented on data/config/base_config.yml
Relative Pfade bitte. Außerdem gibt es kein Grund, die Attribute in der YAML in Capslock zu schreiben, besonders weil du manche (L2Regularisation...) nicht in Caps schreibst. Btw auch hier snake_case, also l2_regularisation_factor

2024-05-11 20:23 UTC, luca-nickel commented on README.md
Wegen der Projektstruktur müssen wir später nochmal gucken. Das mit den "&ensp;" gefällt mir nicht wirklich

2024-05-11 20:23 UTC, luca-nickel commented on src/logging/export_service.py
Ich habe hier schonmal angefangen, die Methodennamen zu fixen (snake_case), aber die Namen der Methoden sind sehr lang. Sollte man vielleicht sich neue Namen überlegen. Und wozu GAFs? Ist das noch aus dem DL Projekt?

2024-05-11 20:23 UTC, luca-nickel commented on src/preprocessing/transformer_service.py
Habe auch hier mal alle Case Style Sachen gefixed. Code ist glaube ich erstmal okay so

2024-05-11 20:23 UTC, luca-nickel commented on trainer.py
Habe auch hier schon ein bisschen gearbeitet. Code funktioniert wahrscheinlich nicht mehr, weil die Methoden aus dem Export Service umbenannt wurden. Die Methoden hier sind sehr lang und haben zu viele Parameter, die unerklärliche Namen haben. Allein daran, wie Black das formattiert, sieht man schon, dass das nicht wirklich clean geschrieben ist. Das müssen wir auf jeden Fall noch mal aufräumen hier

2024-05-12 08:03 UTC, Agueney commented on src/bounding_boxes/fgvs_aircraft_custom_dataset.py
ne für bounding boxes gibt es kein dataset, die art wie die Labels gesetzt werden ist unterschiedlich weils ja keine Klasse gibt hatte ich am Anfang versucht und wurde sehr hässlich

2024-05-12 08:07 UTC, Agueney commented on src/logging/export_service.py
die klasse ist eigentlich unnötig habe sie nur rein gepackt als zwischenlösung, dachte wir nehmen Tensorboard

2024-05-12 08:10 UTC, Agueney commented on trainer.py
ja das logging ist schrecklich, habe ich mich nie wirklich drum gekümmert aber lass uns lieber tensorboard nehmen oder=

2024-05-12 12:17 UTC, luca-nickel reviewed
Sieht bisher gut aus

2024-05-12 12:19 UTC, luca-nickel approved these changes
Approve changes

2024-05-12 12:21 UTC, merged